export const MAX_HEIGHT_STRIP = 100;
export const DEFAULT_STRIP_ARRAY_LENGTH = 10;
export const SHUFFLE_DELAY_IN_MILLISECONDS = 1000;
export const DEFAULT_SORT_STEP_DELAY_IN_SECONDS = 1;

export const RANDOM_SORT_TYPE = "random";
